# Playground Config:
# $ graphql playground
projects:
  app_localidades:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:${env:APP_PORT}
  prisma_admin:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml